import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QR Code as a Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>QR Code</h1>

        <div style={{ display: "flex", gap: 10 }}>
          <img
            className={styles.avatar}
            src="/api/code?size=200&text=https://github.com/dephraiim/qrcode"
            width={200}
            height={200}
            style={{ margin: "10px" }}
          />
        </div>
      </main>
    </div>
  );
}
