import Head from "next/head";
import styles from "../styles/Home.module.css";
import qrcode from "qrcode";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QR Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>QR Code</h1>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const code = await qrcode.toDataURL("hello");

  console.log(code);

  return { props: {} };
};
